title: alexford.io
description: >- # this means to ignore newlines until "baseurl:"
  A web developer/designer/musician in Columbus Ohio, working mostly in Rails, sharing things he learns and finds interesting.
baseurl: "/" # the subpath of your site, e.g. /blog
permalink: /:year/:month/:day/:title:output_ext

url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: alexford
github_username:  alexford
author: Alex Ford
email: alexford87@me.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
